// VC directory data. Edit this array to add/update firms — the UI re-renders from it automatically.
// tier: 'ai-mega' | 'generalist' | 'ai-native' | 'accelerator'
// signal: 1 (software-first, AI opportunistic) – 2 (heavy, growing AI allocation) – 3 (AI is the primary thesis)
// url: portfolio job board or firm site; null when no confirmed public link exists
// noBoard: true when url points to the firm's main site rather than a dedicated jobs board

const VC_FIRMS = [
  // --- AI-first & AI-heavy mega funds ---
  { id: "andreessen-horowitz", name: "Andreessen Horowitz", short: "a16z", tier: "ai-mega", aum: "~$90B AUM", focus: "Full-stack generalist with dedicated AI infra & apps funds", signal: 3, note: "OpenAI, World Labs, Databricks", url: "https://jobs.a16z.com", urlLabel: "jobs.a16z.com", inList: true, noBoard: false },
  { id: "sequoia-capital", name: "Sequoia Capital", tier: "ai-mega", aum: "~$56B AUM", focus: "Seed through growth; enterprise software backbone", signal: 3, note: "OpenAI, xAI", url: "https://jobs.sequoiacap.com", urlLabel: "jobs.sequoiacap.com", inList: true, noBoard: false },
  { id: "thrive", name: "Thrive Capital", tier: "ai-mega", aum: null, focus: "Concentrated growth bets, software-first", signal: 3, note: "Lead across multiple OpenAI rounds", url: "https://jobs.thrivecap.com", urlLabel: "jobs.thrivecap.com", inList: true, noBoard: false },
  { id: "founders-fund", name: "Founders Fund", tier: "ai-mega", aum: null, focus: "Contrarian deep tech & software", signal: 3, note: "Anthropic, Safe Superintelligence", url: "https://foundersfund.com/portfolio/", urlLabel: "foundersfund.com/portfolio", inList: true, noBoard: false },
  { id: "khosla", name: "Khosla Ventures", tier: "ai-mega", aum: null, focus: "Early-stage, high-conviction technical bets", signal: 3, note: "OpenAI's earliest major VC backer", url: "https://jobs.khoslaventures.com/jobs", urlLabel: "jobs.khoslaventures.com", inList: false, noBoard: false },
  { id: "general-catalyst", name: "General Catalyst", tier: "ai-mega", aum: null, focus: "Software + health, “global growth investing”", signal: 2, note: "Anthropic, applied-AI health bets", url: "https://jobs.generalcatalyst.com", urlLabel: "jobs.generalcatalyst.com", inList: false, noBoard: false },
  { id: "coatue", name: "Coatue Management", tier: "ai-mega", aum: null, focus: "Crossover hedge fund / VC, tech-concentrated", signal: 3, note: "Heavy in AI mega-rounds", url: "https://coatue.com", urlLabel: "coatue.com", inList: false, noBoard: true },
  { id: "insight-partners", name: "Insight Partners", tier: "ai-mega", aum: "~$90B AUM", focus: "Enterprise software growth equity", signal: 2, note: "Expanding AI infra/apps thesis", url: "https://jobs.insightpartners.com/jobs", urlLabel: "jobs.insightpartners.com", inList: false, noBoard: false },
  { id: "tiger-global", name: "Tiger Global Management", tier: "ai-mega", aum: "~$58.5B AUM", focus: "Cross-stage internet & software", signal: 2, note: "Broad AI mega-round participant", url: "https://tigerglobal.com", urlLabel: "tigerglobal.com", inList: false, noBoard: true },
  { id: "iconiq", name: "ICONIQ Growth", tier: "ai-mega", aum: null, focus: "Growth-stage enterprise SaaS & AI", signal: 2, note: "OpenAI, enterprise AI stack", url: "https://job-boards.greenhouse.io/iconiq", urlLabel: "iconiq careers", inList: false, noBoard: false },

  // --- Software & growth generalists ---
  { id: "accel", name: "Accel", tier: "generalist", aum: null, focus: "Enterprise & consumer software, all stages", signal: 2, note: null, url: "https://jobs.accel.com", urlLabel: "jobs.accel.com", inList: true, noBoard: false },
  { id: "kleiner-perkins", name: "Kleiner Perkins", tier: "generalist", aum: null, focus: "Storied Sand Hill Road generalist", signal: 2, note: null, url: "https://jobs.kleinerperkins.com", urlLabel: "jobs.kleinerperkins.com", inList: true, noBoard: false },
  { id: "nea", name: "New Enterprise Associates", short: "NEA", tier: "generalist", aum: null, focus: "One of the largest multi-stage generalists", signal: 1, note: null, url: "https://careers.nea.com", urlLabel: "careers.nea.com", inList: true, noBoard: false },
  { id: "bessemer", name: "Bessemer Venture Partners", tier: "generalist", aum: null, focus: "Cloud/SaaS pioneer, “roadmap” theses", signal: 2, note: null, url: "https://jobs.bvp.com", urlLabel: "jobs.bvp.com", inList: true, noBoard: false },
  { id: "lightspeed", name: "Lightspeed Venture Partners", tier: "generalist", aum: null, focus: "Enterprise, consumer, fintech", signal: 2, note: null, url: "https://jobs.lsvp.com", urlLabel: "jobs.lsvp.com", inList: true, noBoard: false },
  { id: "norwest", name: "Norwest Venture Partners", tier: "generalist", aum: null, focus: "Growth equity, software & healthcare", signal: 1, note: null, url: "https://careers.nvp.com", urlLabel: "careers.nvp.com", inList: true, noBoard: false },
  { id: "greylock", name: "Greylock Partners", tier: "generalist", aum: null, focus: "Early-stage enterprise & infra specialist", signal: 2, note: null, url: "https://jobs.greylock.com/jobs", urlLabel: "jobs.greylock.com", inList: false, noBoard: false },
  { id: "menlo", name: "Menlo Ventures", tier: "generalist", aum: null, focus: "Enterprise infra; runs an Anthropic SPV", signal: 2, note: null, url: "https://jobs.menlovc.com/jobs", urlLabel: "jobs.menlovc.com", inList: false, noBoard: false },
  { id: "redpoint", name: "Redpoint Ventures", tier: "generalist", aum: null, focus: "Infra & enterprise software, early-stage", signal: 1, note: null, url: "https://careers.redpoint.com", urlLabel: "careers.redpoint.com", inList: false, noBoard: false },
  { id: "index-ventures", name: "Index Ventures", tier: "generalist", aum: null, focus: "Transatlantic, developer tools & SaaS", signal: 2, note: null, url: "https://www.indexventures.com/startup-jobs", urlLabel: "indexventures.com/startup-jobs", inList: false, noBoard: false },
  { id: "craft", name: "Craft Ventures", tier: "generalist", aum: null, focus: "Operator-led, SaaS & marketplaces", signal: 1, note: null, url: "https://jobs.craftventures.com/jobs", urlLabel: "jobs.craftventures.com", inList: false, noBoard: false },
  { id: "notable-capital", name: "Notable Capital", short: "fka GGV", tier: "generalist", aum: null, focus: "Cross-border enterprise & consumer tech", signal: 1, note: null, url: "https://jobs.notablecap.com", urlLabel: "jobs.notablecap.com", inList: false, noBoard: false },
  { id: "battery", name: "Battery Ventures", tier: "generalist", aum: null, focus: "Infra, software, industrial tech", signal: 1, note: null, url: "https://batteryventures.com", urlLabel: "batteryventures.com", inList: false, noBoard: true },
  { id: "benchmark", name: "Benchmark", tier: "generalist", aum: null, focus: "Small-partnership, high-conviction early-stage", signal: 2, note: "Perplexity", url: "https://benchmark.com", urlLabel: "benchmark.com", inList: false, noBoard: true },
  { id: "ivp", name: "IVP", tier: "generalist", aum: null, focus: "Late-stage growth equity", signal: 1, note: null, url: "https://careers.ivp.com", urlLabel: "careers.ivp.com", inList: false, noBoard: false },
  { id: "crv", name: "CRV", tier: "generalist", aum: null, focus: "Early-stage enterprise & fintech", signal: 1, note: null, url: "https://jobs.crv.com", urlLabel: "jobs.crv.com", inList: false, noBoard: false },
  { id: "mayfield", name: "Mayfield", tier: "generalist", aum: null, focus: "Enterprise & “people-first” AI", signal: 1, note: null, url: "https://mayfield.com", urlLabel: "mayfield.com", inList: false, noBoard: true },
  { id: "emergence", name: "Emergence Capital", tier: "generalist", aum: null, focus: "Enterprise SaaS specialist", signal: 1, note: null, url: "https://emergencecap.com", urlLabel: "emergencecap.com", inList: false, noBoard: true },
  { id: "scale-vp", name: "Scale Venture Partners", tier: "generalist", aum: null, focus: "B2B software growth", signal: 1, note: null, url: "https://jobs.scalevp.com", urlLabel: "jobs.scalevp.com", inList: false, noBoard: false },
  { id: "sapphire", name: "Sapphire Ventures", tier: "generalist", aum: null, focus: "Growth-stage enterprise software", signal: 1, note: null, url: "https://jobs.sapphireventures.com", urlLabel: "jobs.sapphireventures.com", inList: false, noBoard: false },

  // --- AI-native specialists ---
  { id: "conviction", name: "Conviction", tier: "ai-native", aum: null, focus: "AI-native SaaS — founded by Sarah Guo (ex-Greylock)", signal: 3, note: "Harvey, Mistral AI, Sierra", url: "https://www.conviction.com", urlLabel: "conviction.com", inList: false, noBoard: false },
  { id: "radical", name: "Radical Ventures", tier: "ai-native", aum: "$1.45B AUM", focus: "AI-only mandate, Toronto/SF", signal: 3, note: "LPs incl. Geoffrey Hinton, Fei-Fei Li", url: null, urlLabel: null, inList: false, noBoard: false },
  { id: "aix", name: "AIX Ventures", tier: "ai-native", aum: "$252M AUM", focus: "Technical AI diligence specialists", signal: 3, note: "Founded by ML researchers", url: null, urlLabel: null, inList: false, noBoard: false },
  { id: "amplify", name: "Amplify Partners", tier: "ai-native", aum: null, focus: "Dev-tools & infra, AI-heavy since seed", signal: 3, note: "“First investor for technical founders”", url: "https://talent.amplifypartners.com", urlLabel: "talent.amplifypartners.com", inList: false, noBoard: false },
  { id: "basis-set", name: "Basis Set Ventures", tier: "ai-native", aum: "$850M AUM", focus: "Applied AI & enterprise automation", signal: 3, note: "Founded by Lan Xuezhao", url: "https://jobs.basisset.com", urlLabel: "jobs.basisset.com", inList: false, noBoard: false },
  { id: "air-street", name: "Air Street Capital", tier: "ai-native", aum: null, focus: "AI-first tech & life sciences (London-based, invests in the US)", signal: 3, note: "Run by Nathan Benaich", url: "https://www.airstreet.com", urlLabel: "airstreet.com", inList: false, noBoard: false },

  // --- Accelerator ---
  { id: "y-combinator", name: "Y Combinator", tier: "accelerator", aum: null, focus: "Seed accelerator — highest-volume board for early-stage software/AI roles", signal: 2, note: "Not a check-writing growth VC", url: "https://www.workatastartup.com", urlLabel: "workatastartup.com", inList: true, noBoard: false },
  // --- Firms added after probing for scrapeable portfolio boards ---
  { id: "first-round", name: "First Round Capital", tier: "generalist", aum: null, focus: "Seed-stage generalist with a large operating community", signal: 2, note: null, url: "https://jobs.firstround.com", urlLabel: "jobs.firstround.com", inList: false, noBoard: false },
  { id: "initialized", name: "Initialized Capital", tier: "generalist", aum: null, focus: "Seed-stage software and infrastructure", signal: 2, note: null, url: "https://jobs.initialized.com", urlLabel: "jobs.initialized.com", inList: false, noBoard: false },
  { id: "bain-capital-ventures", name: "Bain Capital Ventures", tier: "generalist", aum: null, focus: "Seed to growth across enterprise software and fintech", signal: 2, note: null, url: "https://jobs.baincapitalventures.com", urlLabel: "jobs.baincapitalventures.com", inList: false, noBoard: false },
  { id: "felicis", name: "Felicis Ventures", tier: "generalist", aum: null, focus: "Early-stage generalist, global footprint", signal: 2, note: null, url: "https://jobs.felicis.com", urlLabel: "jobs.felicis.com", inList: false, noBoard: false },
  { id: "point72-ventures", name: "Point72 Ventures", tier: "generalist", aum: null, focus: "Early-stage enterprise, fintech and AI", signal: 2, note: null, url: "https://jobs.p72.vc", urlLabel: "jobs.p72.vc", inList: false, noBoard: false },
  { id: "forerunner", name: "Forerunner Ventures", tier: "generalist", aum: null, focus: "Consumer and commerce, early stage", signal: 1, note: null, url: "https://jobs.forerunnerventures.com", urlLabel: "jobs.forerunnerventures.com", inList: false, noBoard: false },
  { id: "costanoa", name: "Costanoa Ventures", tier: "generalist", aum: null, focus: "Seed and Series A B2B software", signal: 2, note: null, url: "https://jobs.costanoavc.com", urlLabel: "jobs.costanoavc.com", inList: false, noBoard: false },
  { id: "qed", name: "QED Investors", tier: "generalist", aum: null, focus: "Fintech specialist, seed through growth", signal: 1, note: null, url: "https://careers.qedinvestors.com", urlLabel: "careers.qedinvestors.com", inList: false, noBoard: false },
  { id: "uncork", name: "Uncork Capital", tier: "generalist", aum: null, focus: "Seed-stage generalist", signal: 1, note: null, url: "https://jobs.uncorkcapital.com", urlLabel: "jobs.uncorkcapital.com", inList: false, noBoard: false },
  { id: "signalfire", name: "SignalFire", tier: "generalist", aum: null, focus: "Seed and Series A, data-driven sourcing", signal: 2, note: null, url: "https://jobs.signalfire.com", urlLabel: "jobs.signalfire.com", inList: false, noBoard: false },
  { id: "8vc", name: "8VC", tier: "generalist", aum: null, focus: "Enterprise software, healthcare and defence tech", signal: 2, note: null, url: "https://jobs.8vc.com", urlLabel: "jobs.8vc.com", inList: false, noBoard: false },
  { id: "canaan", name: "Canaan Partners", tier: "generalist", aum: null, focus: "Early-stage technology and healthcare", signal: 1, note: null, url: "https://careers.canaan.com", urlLabel: "careers.canaan.com", inList: false, noBoard: false },
  { id: "wing", name: "Wing Venture Capital", tier: "generalist", aum: null, focus: "Early-stage enterprise software", signal: 2, note: null, url: "https://careers.wing.vc", urlLabel: "careers.wing.vc", inList: false, noBoard: false },
  { id: "madrona", name: "Madrona Venture Group", tier: "generalist", aum: null, focus: "Pacific Northwest early stage, cloud and AI", signal: 2, note: null, url: "https://jobs.madrona.com", urlLabel: "jobs.madrona.com", inList: false, noBoard: false },
  { id: "primary", name: "Primary Venture Partners", tier: "generalist", aum: null, focus: "NYC-focused seed stage", signal: 1, note: null, url: "https://jobs.primary.vc", urlLabel: "jobs.primary.vc", inList: false, noBoard: false },
  { id: "lerer-hippeau", name: "Lerer Hippeau", tier: "generalist", aum: null, focus: "NYC seed-stage generalist", signal: 1, note: null, url: "https://jobs.lererhippeau.com", urlLabel: "jobs.lererhippeau.com", inList: false, noBoard: false },
  { id: "true-ventures", name: "True Ventures", tier: "generalist", aum: null, focus: "Seed-stage technology generalist", signal: 1, note: null, url: "https://jobs.trueventures.com", urlLabel: "jobs.trueventures.com", inList: false, noBoard: false },
  { id: "greycroft", name: "Greycroft", tier: "generalist", aum: null, focus: "Early and growth stage, consumer and enterprise", signal: 1, note: null, url: "https://jobs.greycroft.com", urlLabel: "jobs.greycroft.com", inList: false, noBoard: false },
  { id: "upfront", name: "Upfront Ventures", tier: "generalist", aum: null, focus: "LA-based early stage", signal: 1, note: null, url: "https://jobs.upfront.com", urlLabel: "jobs.upfront.com", inList: false, noBoard: false },
  { id: "m13", name: "M13", tier: "generalist", aum: null, focus: "Consumer and commerce technology", signal: 1, note: null, url: "https://jobs.m13.co", urlLabel: "jobs.m13.co", inList: false, noBoard: false },
  { id: "freestyle", name: "Freestyle Capital", tier: "generalist", aum: null, focus: "Seed-stage software", signal: 1, note: null, url: "https://jobs.freestyle.vc", urlLabel: "jobs.freestyle.vc", inList: false, noBoard: false },
  { id: "homebrew", name: "Homebrew", tier: "generalist", aum: null, focus: "Seed-stage, now investing as an evergreen fund", signal: 1, note: null, url: "https://careers.homebrew.co", urlLabel: "careers.homebrew.co", inList: false, noBoard: false },
  { id: "obvious", name: "Obvious Ventures", tier: "generalist", aum: null, focus: "World-positive early-stage investing", signal: 1, note: null, url: "https://jobs.obvious.com", urlLabel: "jobs.obvious.com", inList: false, noBoard: false },
  { id: "nfx", name: "NFX", tier: "generalist", aum: null, focus: "Seed-stage, network-effects thesis", signal: 1, note: null, url: "https://jobs.nfx.com", urlLabel: "jobs.nfx.com", inList: false, noBoard: false },
  { id: "sierra-ventures", name: "Sierra Ventures", tier: "generalist", aum: null, focus: "Early-stage enterprise technology", signal: 1, note: null, url: "https://careers.sierraventures.com", urlLabel: "careers.sierraventures.com", inList: false, noBoard: false },
  { id: "georgian", name: "Georgian", tier: "generalist", aum: null, focus: "Growth-stage B2B software with an applied-AI practice", signal: 2, note: null, url: "https://careers.georgian.io", urlLabel: "careers.georgian.io", inList: false, noBoard: false },
  { id: "lux-capital", name: "Lux Capital", tier: "ai-native", aum: null, focus: "Deep tech and frontier science, AI-heavy", signal: 3, note: null, url: "https://jobs.luxcapital.com", urlLabel: "jobs.luxcapital.com", inList: false, noBoard: false },
  { id: "dcvc", name: "DCVC", tier: "ai-native", aum: null, focus: "Deep tech and computational science", signal: 3, note: null, url: "https://jobs.dcvc.com", urlLabel: "jobs.dcvc.com", inList: false, noBoard: false },
  { id: "gradient", name: "Gradient Ventures", tier: "ai-native", aum: null, focus: "Google's AI-focused early-stage fund", signal: 3, note: null, url: "https://careers.gradient.com", urlLabel: "careers.gradient.com", inList: false, noBoard: false },
  { id: "playground-global", name: "Playground Global", tier: "ai-native", aum: null, focus: "Deep tech, robotics and silicon", signal: 3, note: null, url: "https://careers.playground.global", urlLabel: "careers.playground.global", inList: false, noBoard: false },
  { id: "innovation-endeavors", name: "Innovation Endeavors", tier: "ai-native", aum: null, focus: "Early-stage deep tech and applied AI", signal: 3, note: null, url: "https://jobs.innovationendeavors.com", urlLabel: "jobs.innovationendeavors.com", inList: false, noBoard: false },
  { id: "zetta", name: "Zetta Venture Partners", tier: "ai-native", aum: null, focus: "AI-first seed investing", signal: 3, note: null, url: "https://careers.zettavp.com", urlLabel: "careers.zettavp.com", inList: false, noBoard: false },
  { id: "glasswing", name: "Glasswing Ventures", tier: "ai-native", aum: null, focus: "AI-native seed and Series A", signal: 3, note: null, url: "https://jobs.glasswing.vc", urlLabel: "jobs.glasswing.vc", inList: false, noBoard: false },
];

const TIER_META = {
  "ai-mega": { label: "AI-First & AI-Heavy Mega Funds", short: "AI-First Mega Funds" },
  "generalist": { label: "Software & Growth Generalists", short: "Generalists" },
  "ai-native": { label: "AI-Native Specialists", short: "AI-Native" },
  "accelerator": { label: "Accelerators", short: "Accelerators" },
};
